import { TextItem, TextMarkedContent } from "pdfjs-dist/types/src/display/api";

export function isTextItem(textItem: TextItem | TextMarkedContent): textItem is TextItem {
    return Object.hasOwn(textItem, 'transform');
};


// All the possible operations for an operator list.
export const OPS = {
    1: 'dependency',
    2: 'setLineWidth',
    3: 'setLineCap',
    4: 'setLineJoin',
    5: 'setMiterLimit',
    6: 'setDash',
    7: 'setRenderingIntent',
    8: 'setFlatness',
    9: 'setGState',
    10: 'save',
    11: 'restore',
    12: 'transform',
    13: 'moveTo',
    14: 'lineTo',
    15: 'curveTo',
    16: 'curveTo2',
    17: 'curveTo3',
    18: 'closePath',
    19: 'rectangle',
    20: 'stroke',
    21: 'closeStroke',
    22: 'fill',
    23: 'eoFill',
    24: 'fillStroke',
    25: 'eoFillStroke',
    26: 'closeFillStroke',
    27: 'closeEOFillStroke',
    28: 'endPath',
    29: 'clip',
    30: 'eoClip',
    31: 'beginText',
    32: 'endText',
    33: 'setCharSpacing',
    34: 'setWordSpacing',
    35: 'setHScale',
    36: 'setLeading',
    37: 'setFont',
    38: 'setTextRenderingMode',
    39: 'setTextRise',
    40: 'moveText',
    41: 'setLeadingMoveText',
    42: 'setTextMatrix',
    43: 'nextLine',
    44: 'showText',
    45: 'showSpacedText',
    46: 'nextLineShowText',
    47: 'nextLineSetSpacingShowText',
    48: 'setCharWidth',
    49: 'setCharWidthAndBounds',
    50: 'setStrokeColorSpace',
    51: 'setFillColorSpace',
    52: 'setStrokeColor',
    53: 'setStrokeColorN',
    54: 'setFillColor',
    55: 'setFillColorN',
    56: 'setStrokeGray',
    57: 'setFillGray',
    58: 'setStrokeRGBColor',
    59: 'setFillRGBColor',
    60: 'setStrokeCMYKColor',
    61: 'setFillCMYKColor',
    62: 'shadingFill',
    63: 'beginInlineImage',
    64: 'beginImageData',
    65: 'endInlineImage',
    66: 'paintXObject',
    67: 'markPoint',
    68: 'markPointProps',
    69: 'beginMarkedContent',
    70: 'beginMarkedContentProps',
    71: 'endMarkedContent',
    72: 'beginCompat',
    73: 'endCompat',
    74: 'paintFormXObjectBegin',
    75: 'paintFormXObjectEnd',
    76: 'beginGroup',
    77: 'endGroup',
    78: 'beginAnnotations',
    79: 'endAnnotations',
    80: 'beginAnnotation',
    81: 'endAnnotation',
    82: 'paintJpegXObject',
    83: 'paintImageMaskXObject',
    84: 'paintImageMaskXObjectGroup',
    85: 'paintImageXObject',
    86: 'paintInlineImageXObject',
    87: 'paintInlineImageXObjectGroup',
    88: 'paintImageXObjectRepeat',
    89: 'paintImageMaskXObjectRepeat',
    90: 'paintSolidColorImageMask',
    91: 'constructPath',
} as const;